# Generated by Django 2.0.2 on 2018-02-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgwidget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='tg_auth_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='tg_first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='tg_hash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='tg_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='tg_last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='tg_photo_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='tg_username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
