# Generated by Django 2.0 on 2018-02-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgwidget', '0002_auto_20180209_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguser',
            name='tg_hash',
        ),
        migrations.AlterField(
            model_name='tguser',
            name='tg_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
